In [ ]:
import os
import pickle
from pathlib import Path

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [2]:
DRIVE_DIRECTORY = Path.cwd().parent / "data"
with open(os.path.join(DRIVE_DIRECTORY, "credit.pkl"), "rb") as f:
    X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = (
        pickle.load(f)
    )

In [3]:
resultados_arvores = []
resultados_random_forest = []
resultados_knn = []
resultados_logistica = []
resultados_svm = []
# resultados_rede_neural = []
for i in range(30):
    kfold = KFold(n_splits=10, shuffle=True, random_state=i)
    arvore = DecisionTreeClassifier(
        criterion="entropy", min_samples_leaf=1, min_samples_split=5, splitter="best"
    )
    random_forest = RandomForestClassifier(
        criterion="entropy", min_samples_leaf=1, min_samples_split=5, n_estimators=10
    )
    knn = KNeighborsClassifier(n_neighbors=17, p=1)
    regresao_log = LogisticRegression(C=1.0, solver="lbfgs", tol=0.0001)
    svm = SVC(C=4.0, kernel="rbf", tol=0.1)
    rede_neural = MLPClassifier(
        activation="relu", batch_size=7, solver="adam", tol=0.0000001
    )
    scores = cross_val_score(
        arvore, X_credit_treinamento, y_credit_treinamento, cv=kfold
    )
    resultados_arvores.append(scores.mean())
    scores = cross_val_score(
        random_forest, X_credit_treinamento, y_credit_treinamento, cv=kfold
    )
    resultados_random_forest.append(scores.mean())
    scores = cross_val_score(knn, X_credit_treinamento, y_credit_treinamento, cv=kfold)
    resultados_knn.append(scores.mean())
    scores = cross_val_score(
        regresao_log, X_credit_treinamento, y_credit_treinamento, cv=kfold
    )
    resultados_logistica.append(scores.mean())
    scores = cross_val_score(svm, X_credit_treinamento, y_credit_treinamento, cv=kfold)
    resultados_svm.append(scores.mean())
    # scores = cross_val_score(
    #     rede_neural, X_credit_treinamento, y_credit_treinamento, cv=kfold
    # )
    # resultados_rede_neural.append(scores.mean())

In [4]:
print(max(resultados_arvores))
print(max(resultados_random_forest))
print(max(resultados_knn))
print(max(resultados_logistica))
print(max(resultados_svm))
# print(max(resultados_rede_neural))

0.9906666666666666
0.9866666666666666
0.9853333333333334
0.9486666666666667
0.9866666666666667

In [5]:
resultados = pd.DataFrame({
    'Arvore': resultados_arvores,
    'Random Forest': resultados_random_forest,
    'KNN': resultados_knn,
    'Regresão Logistica': resultados_logistica,
    'SVM': resultados_svm
})

In [6]:
resultados

      Arvore  Random Forest       KNN  Regresão Logistica       SVM
0   0.986667       0.982000  0.982000            0.945333  0.982000
1   0.987333       0.984667  0.984667            0.947333  0.981333
2   0.986000       0.980000  0.982000            0.946000  0.986000
3   0.986667       0.985333  0.982000            0.945333  0.984667
4   0.984667       0.982000  0.982667            0.948667  0.982000
5   0.984000       0.984667  0.982000            0.945333  0.982000
6   0.988667       0.985333  0.983333            0.944667  0.982667
7   0.986667       0.986000  0.982000            0.946000  0.982000
8   0.984667       0.984667  0.983333            0.948000  0.984667
9   0.984667       0.982667  0.985333            0.945333  0.985333
10  0.986667       0.982000  0.980000            0.948000  0.984000
11  0.987333       0.983333  0.982667            0.948000  0.985333
12  0.986667       0.984667  0.980667            0.947333  0.986000
13  0.985333       0.981333  0.980667            0.944667  0.984000
14  0.983333       0.985333  0.979333            0.947333  0.986667
15  0.986667       0.985333  0.983333            0.947333  0.984000
16  0.987333       0.985333  0.984667            0.946667  0.982000
17  0.986000       0.985333  0.983333            0.945333  0.982667
18  0.988000       0.984000  0.982000            0.947333  0.983333
19  0.989333       0.984000  0.984667            0.946000  0.984000
20  0.990667       0.986667  0.984667            0.946000  0.985333
21  0.986667       0.983333  0.984000            0.947333  0.983333
22  0.985333       0.985333  0.978000            0.944667  0.983333
23  0.987333       0.980000  0.984667            0.944667  0.986000
24  0.987333       0.984000  0.980000            0.945333  0.986000
25  0.986667       0.984000  0.982667            0.948000  0.983333
26  0.987333       0.980000  0.981333            0.944667  0.985333
27  0.984000       0.980667  0.980667            0.945333  0.983333
28  0.986667       0.984000  0.980667            0.948000  0.984000
29  0.987333       0.984000  0.984000            0.947333  0.982000

In [7]:
resultados.describe()

          Arvore  Random Forest        KNN  Regresão Logistica        SVM
count  30.000000      30.000000  30.000000           30.000000  30.000000
mean    0.986533       0.983667   0.982378            0.946378   0.983889
std     0.001589       0.001884   0.001834            0.001283   0.001527
min     0.983333       0.980000   0.978000            0.944667   0.981333
25%     0.985500       0.982167   0.980833            0.945333   0.982667
50%     0.986667       0.984000   0.982333            0.946000   0.984000
75%     0.987333       0.985333   0.983833            0.947333   0.985333
max     0.990667       0.986667   0.985333            0.948667   0.986667

In [8]:
resultados.var()

Arvore                0.000003
Random Forest         0.000004
KNN                   0.000003
Regresão Logistica    0.000002
SVM                   0.000002
dtype: float64

In [9]:
(resultados.std() / resultados.mean()) * 100

Arvore                0.161093
Random Forest         0.191486
KNN                   0.186645
Regresão Logistica    0.135544
SVM                   0.155211
dtype: float64