# **Regressão**

In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor

DRIVE_DIRECTORY = Path.cwd().parent / "data"

## Regressão Polinomial

### Base plano de saúde

In [2]:
base_plano_saude2 = pd.read_csv(os.path.join(DRIVE_DIRECTORY, "plano_saude2.csv"))
base_plano_saude2

   idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [3]:
X_planos_saude2 = base_plano_saude2.iloc[:, 0:1].values
y_planos_saude2 = base_plano_saude2.iloc[:, 1].values
X_planos_saude2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [4]:
y_planos_saude2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [5]:
poly = PolynomialFeatures(degree=2)
X_planos_saude2_poly = poly.fit_transform(X_planos_saude2)
X_planos_saude2.shape

(10, 1)

In [6]:
X_planos_saude2_poly.shape

(10, 3)

In [7]:
regressor_saude_polinomial = LinearRegression()
regressor_saude_polinomial.fit(X_planos_saude2_poly, y_planos_saude2)

LinearRegression()

In [8]:
regressor_saude_polinomial.intercept_

np.float64(7133.836363636174)

In [9]:
regressor_saude_polinomial.coef_

array([   0.        , -469.89393939,    7.82121212])

In [10]:
novo = [[40]]

In [11]:
novo = poly.transform(novo)
novo

array([[1.0e+00, 4.0e+01, 1.6e+03]])

In [12]:
regressor_saude_polinomial.predict(novo)

array([852.01818182])

In [13]:
previsoes = regressor_saude_polinomial.predict(X_planos_saude2_poly)
previsoes

array([1209.81818182,  463.6969697 ,  108.63636364,  144.63636364,
        571.6969697 , 1389.81818182, 2599.        , 4199.24242424,
       6190.54545455, 8572.90909091])

In [14]:
grafico = px.scatter(x=X_planos_saude2[:, 0], y=y_planos_saude2)
grafico.add_scatter(x=X_planos_saude2[:, 0], y=previsoes, name='Regressão')
grafico.show()

### Base preço das casas

In [15]:
base_casas = pd.read_csv(os.path.join(DRIVE_DIRECTORY, 'house_prices.csv'))
base_casas

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [16]:
X_casas = base_casas.iloc[:, 3:19].values
X_casas

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ...,  9.81780e+04,
         4.75112e+01, -1.22257e+02],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ...,  9.81250e+04,
         4.77210e+01, -1.22319e+02],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ...,  9.80280e+04,
         4.77379e+01, -1.22233e+02],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75944e+01, -1.22299e+02],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ...,  9.80270e+04,
         4.75345e+01, -1.22069e+02],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75941e+01, -1.22299e+02]], shape=(21613, 16))

In [17]:
y_casas = base_casas.iloc[:, 2].values
y_casas

array([221900., 538000., 180000., ..., 402101., 400000., 325000.],
      shape=(21613,))

In [18]:
X_casas_train, X_casas_test, y_casas_train, y_casas_test = train_test_split(
    X_casas, y_casas, test_size=0.3, random_state=0
)

In [19]:
X_casas_train.shape, X_casas_test.shape

((15129, 16), (6484, 16))

In [20]:
poly = PolynomialFeatures(degree=2)
X_casas_train_poly = poly.fit_transform(X_casas_train)
X_casas_test_poly = poly.transform(X_casas_test)

In [21]:
X_casas_train_poly.shape, X_casas_train_poly.shape

((15129, 153), (15129, 153))

In [22]:
regressor_casas_poly = LinearRegression()
regressor_casas_poly.fit(X_casas_train_poly, y_casas_train)

LinearRegression()

In [23]:
regressor_casas_poly.score(X_casas_train_poly, y_casas_train)

0.7924863532450124

In [24]:
regressor_casas_poly.score(X_casas_test_poly, y_casas_test)

0.7945486446460233

In [25]:
previsoes = regressor_casas_poly.predict(X_casas_test_poly)
previsoes

array([ 442197.02037959, 1956399.28712605,  576589.98593022, ...,
        350582.4564456 ,  246776.53365998,  221178.81282404],
      shape=(6484,))

In [26]:
mean_absolute_error(y_casas_test, previsoes)

105307.16388193313

## Árvores de decisão

### Base plano saúde

In [27]:
regressor_arvore_saude = DecisionTreeRegressor()
regressor_arvore_saude.fit(X_planos_saude2, y_planos_saude2)

DecisionTreeRegressor()

In [28]:
previsoes = regressor_arvore_saude.predict(X_planos_saude2)
previsoes

array([  470.,   520.,   630.,   830.,  1150.,  1530.,  2040.,  3080.,
        5100., 10100.])

In [29]:
regressor_arvore_saude.score(X_planos_saude2, y_planos_saude2)

1.0

In [30]:
grafico = px.scatter(x=X_planos_saude2.ravel(), y=y_planos_saude2)
grafico.add_scatter(x=X_planos_saude2.ravel(), y=previsoes, name='Regressão')
grafico.show()

In [31]:
X_teste_arvore = np.arange(X_planos_saude2.min(), X_planos_saude2.max(), 0.1)
X_teste_arvore

array([18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. ,
       19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1,
       20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 21. , 21.1, 21.2,
       21.3, 21.4, 21.5, 21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2, 22.3,
       22.4, 22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3, 23.4,
       23.5, 23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.2, 24.3, 24.4, 24.5,
       24.6, 24.7, 24.8, 24.9, 25. , 25.1, 25.2, 25.3, 25.4, 25.5, 25.6,
       25.7, 25.8, 25.9, 26. , 26.1, 26.2, 26.3, 26.4, 26.5, 26.6, 26.7,
       26.8, 26.9, 27. , 27.1, 27.2, 27.3, 27.4, 27.5, 27.6, 27.7, 27.8,
       27.9, 28. , 28.1, 28.2, 28.3, 28.4, 28.5, 28.6, 28.7, 28.8, 28.9,
       29. , 29.1, 29.2, 29.3, 29.4, 29.5, 29.6, 29.7, 29.8, 29.9, 30. ,
       30.1, 30.2, 30.3, 30.4, 30.5, 30.6, 30.7, 30.8, 30.9, 31. , 31.1,
       31.2, 31.3, 31.4, 31.5, 31.6, 31.7, 31.8, 31.9, 32. , 32.1, 32.2,
       32.3, 32.4, 32.5, 32.6, 32.7, 32.8, 32.9, 33. , 33.1, 33.2, 33.3,
       33.4, 33.5, 33.6, 33.7, 33.8, 33.9, 34. , 34.1, 34.2, 34.3, 34.4,
       34.5, 34.6, 34.7, 34.8, 34.9, 35. , 35.1, 35.2, 35.3, 35.4, 35.5,
       35.6, 35.7, 35.8, 35.9, 36. , 36.1, 36.2, 36.3, 36.4, 36.5, 36.6,
       36.7, 36.8, 36.9, 37. , 37.1, 37.2, 37.3, 37.4, 37.5, 37.6, 37.7,
       37.8, 37.9, 38. , 38.1, 38.2, 38.3, 38.4, 38.5, 38.6, 38.7, 38.8,
       38.9, 39. , 39.1, 39.2, 39.3, 39.4, 39.5, 39.6, 39.7, 39.8, 39.9,
       40. , 40.1, 40.2, 40.3, 40.4, 40.5, 40.6, 40.7, 40.8, 40.9, 41. ,
       41.1, 41.2, 41.3, 41.4, 41.5, 41.6, 41.7, 41.8, 41.9, 42. , 42.1,
       42.2, 42.3, 42.4, 42.5, 42.6, 42.7, 42.8, 42.9, 43. , 43.1, 43.2,
       43.3, 43.4, 43.5, 43.6, 43.7, 43.8, 43.9, 44. , 44.1, 44.2, 44.3,
       44.4, 44.5, 44.6, 44.7, 44.8, 44.9, 45. , 45.1, 45.2, 45.3, 45.4,
       45.5, 45.6, 45.7, 45.8, 45.9, 46. , 46.1, 46.2, 46.3, 46.4, 46.5,
       46.6, 46.7, 46.8, 46.9, 47. , 47.1, 47.2, 47.3, 47.4, 47.5, 47.6,
       47.7, 47.8, 47.9, 48. , 48.1, 48.2, 48.3, 48.4, 48.5, 48.6, 48.7,
       48.8, 48.9, 49. , 49.1, 49.2, 49.3, 49.4, 49.5, 49.6, 49.7, 49.8,
       49.9, 50. , 50.1, 50.2, 50.3, 50.4, 50.5, 50.6, 50.7, 50.8, 50.9,
       51. , 51.1, 51.2, 51.3, 51.4, 51.5, 51.6, 51.7, 51.8, 51.9, 52. ,
       52.1, 52.2, 52.3, 52.4, 52.5, 52.6, 52.7, 52.8, 52.9, 53. , 53.1,
       53.2, 53.3, 53.4, 53.5, 53.6, 53.7, 53.8, 53.9, 54. , 54.1, 54.2,
       54.3, 54.4, 54.5, 54.6, 54.7, 54.8, 54.9, 55. , 55.1, 55.2, 55.3,
       55.4, 55.5, 55.6, 55.7, 55.8, 55.9, 56. , 56.1, 56.2, 56.3, 56.4,
       56.5, 56.6, 56.7, 56.8, 56.9, 57. , 57.1, 57.2, 57.3, 57.4, 57.5,
       57.6, 57.7, 57.8, 57.9, 58. , 58.1, 58.2, 58.3, 58.4, 58.5, 58.6,
       58.7, 58.8, 58.9, 59. , 59.1, 59.2, 59.3, 59.4, 59.5, 59.6, 59.7,
       59.8, 59.9, 60. , 60.1, 60.2, 60.3, 60.4, 60.5, 60.6, 60.7, 60.8,
       60.9, 61. , 61.1, 61.2, 61.3, 61.4, 61.5, 61.6, 61.7, 61.8, 61.9,
       62. , 62.1, 62.2, 62.3, 62.4, 62.5, 62.6, 62.7, 62.8, 62.9])

In [32]:
X_teste_arvore = X_teste_arvore.reshape(-1, 1)
X_teste_arvore

array([[18. ],
       [18.1],
       [18.2],
       [18.3],
       [18.4],
       [18.5],
       [18.6],
       [18.7],
       [18.8],
       [18.9],
       [19. ],
       [19.1],
       [19.2],
       [19.3],
       [19.4],
       [19.5],
       [19.6],
       [19.7],
       [19.8],
       [19.9],
       [20. ],
       [20.1],
       [20.2],
       [20.3],
       [20.4],
       [20.5],
       [20.6],
       [20.7],
       [20.8],
       [20.9],
       [21. ],
       [21.1],
       [21.2],
       [21.3],
       [21.4],
       [21.5],
       [21.6],
       [21.7],
       [21.8],
       [21.9],
       [22. ],
       [22.1],
       [22.2],
       [22.3],
       [22.4],
       [22.5],
       [22.6],
       [22.7],
       [22.8],
       [22.9],
       [23. ],
       [23.1],
       [23.2],
       [23.3],
       [23.4],
       [23.5],
       [23.6],
       [23.7],
       [23.8],
       [23.9],
       [24. ],
       [24.1],
       [24.2],
       [24.3],
       [24.4],
       [24.5],
       [24.6],
       [24.7],
       [24.8],
       [24.9],
       [25. ],
       [25.1],
       [25.2],
       [25.3],
       [25.4],
       [25.5],
       [25.6],
       [25.7],
       [25.8],
       [25.9],
       [26. ],
       [26.1],
       [26.2],
       [26.3],
       [26.4],
       [26.5],
       [26.6],
       [26.7],
       [26.8],
       [26.9],
       [27. ],
       [27.1],
       [27.2],
       [27.3],
       [27.4],
       [27.5],
       [27.6],
       [27.7],
       [27.8],
       [27.9],
       [28. ],
       [28.1],
       [28.2],
       [28.3],
       [28.4],
       [28.5],
       [28.6],
       [28.7],
       [28.8],
       [28.9],
       [29. ],
       [29.1],
       [29.2],
       [29.3],
       [29.4],
       [29.5],
       [29.6],
       [29.7],
       [29.8],
       [29.9],
       [30. ],
       [30.1],
       [30.2],
       [30.3],
       [30.4],
       [30.5],
       [30.6],
       [30.7],
       [30.8],
       [30.9],
       [31. ],
       [31.1],
       [31.2],
       [31.3],
       [31.4],
       [31.5],
       [31.6],
       [31.7],
       [31.8],
       [31.9],
       [32. ],
       [32.1],
       [32.2],
       [32.3],
       [32.4],
       [32.5],
       [32.6],
       [32.7],
       [32.8],
       [32.9],
       [33. ],
       [33.1],
       [33.2],
       [33.3],
       [33.4],
       [33.5],
       [33.6],
       [33.7],
       [33.8],
       [33.9],
       [34. ],
       [34.1],
       [34.2],
       [34.3],
       [34.4],
       [34.5],
       [34.6],
       [34.7],
       [34.8],
       [34.9],
       [35. ],
       [35.1],
       [35.2],
       [35.3],
       [35.4],
       [35.5],
       [35.6],
       [35.7],
       [35.8],
       [35.9],
       [36. ],
       [36.1],
       [36.2],
       [36.3],
       [36.4],
       [36.5],
       [36.6],
       [36.7],
       [36.8],
       [36.9],
       [37. ],
       [37.1],
       [37.2],
       [37.3],
       [37.4],
       [37.5],
       [37.6],
       [37.7],
       [37.8],
       [37.9],
       [38. ],
       [38.1],
       [38.2],
       [38.3],
       [38.4],
       [38.5],
       [38.6],
       [38.7],
       [38.8],
       [38.9],
       [39. ],
       [39.1],
       [39.2],
       [39.3],
       [39.4],
       [39.5],
       [39.6],
       [39.7],
       [39.8],
       [39.9],
       [40. ],
       [40.1],
       [40.2],
       [40.3],
       [40.4],
       [40.5],
       [40.6],
       [40.7],
       [40.8],
       [40.9],
       [41. ],
       [41.1],
       [41.2],
       [41.3],
       [41.4],
       [41.5],
       [41.6],
       [41.7],
       [41.8],
       [41.9],
       [42. ],
       [42.1],
       [42.2],
       [42.3],
       [42.4],
       [42.5],
       [42.6],
       [42.7],
       [42.8],
       [42.9],
       [43. ],
       [43.1],
       [43.2],
       [43.3],
       [43.4],
       [43.5],
       [43.6],
       [43.7],
       [43.8],
       [43.9],
       [44. ],
       [44.1],
       [44.2],
       [44.3],
       [44.4],
       [44.5],
       [44.6],
       [44.7],
       [44.8],
       [44.9],
       [45. ],
       [45.1],
       [45.2],
       [45.3],
       [45.4],
       [45.5],
       [45.6],
       [45.7],
       [45.8],
       [45.9],
       [46. ],
       [46.1],
       [46.2],
       [46.3],
       [46.4],
       [46.5],
       [46.6],
       [46.7],
       [46.8],
       [46.9],
       [47. ],
       [47.1],
       [47.2],
       [47.3],
       [47.4],
       [47.5],
       [47.6],
       [47.7],
       [47.8],
       [47.9],
       [48. ],
       [48.1],
       [48.2],
       [48.3],
       [48.4],
       [48.5],
       [48.6],
       [48.7],
       [48.8],
       [48.9],
       [49. ],
       [49.1],
       [49.2],
       [49.3],
       [49.4],
       [49.5],
       [49.6],
       [49.7],
       [49.8],
       [49.9],
       [50. ],
       [50.1],
       [50.2],
       [50.3],
       [50.4],
       [50.5],
       [50.6],
       [50.7],
       [50.8],
       [50.9],
       [51. ],
       [51.1],
       [51.2],
       [51.3],
       [51.4],
       [51.5],
       [51.6],
       [51.7],
       [51.8],
       [51.9],
       [52. ],
       [52.1],
       [52.2],
       [52.3],
       [52.4],
       [52.5],
       [52.6],
       [52.7],
       [52.8],
       [52.9],
       [53. ],
       [53.1],
       [53.2],
       [53.3],
       [53.4],
       [53.5],
       [53.6],
       [53.7],
       [53.8],
       [53.9],
       [54. ],
       [54.1],
       [54.2],
       [54.3],
       [54.4],
       [54.5],
       [54.6],
       [54.7],
       [54.8],
       [54.9],
       [55. ],
       [55.1],
       [55.2],
       [55.3],
       [55.4],
       [55.5],
       [55.6],
       [55.7],
       [55.8],
       [55.9],
       [56. ],
       [56.1],
       [56.2],
       [56.3],
       [56.4],
       [56.5],
       [56.6],
       [56.7],
       [56.8],
       [56.9],
       [57. ],
       [57.1],
       [57.2],
       [57.3],
       [57.4],
       [57.5],
       [57.6],
       [57.7],
       [57.8],
       [57.9],
       [58. ],
       [58.1],
       [58.2],
       [58.3],
       [58.4],
       [58.5],
       [58.6],
       [58.7],
       [58.8],
       [58.9],
       [59. ],
       [59.1],
       [59.2],
       [59.3],
       [59.4],
       [59.5],
       [59.6],
       [59.7],
       [59.8],
       [59.9],
       [60. ],
       [60.1],
       [60.2],
       [60.3],
       [60.4],
       [60.5],
       [60.6],
       [60.7],
       [60.8],
       [60.9],
       [61. ],
       [61.1],
       [61.2],
       [61.3],
       [61.4],
       [61.5],
       [61.6],
       [61.7],
       [61.8],
       [61.9],
       [62. ],
       [62.1],
       [62.2],
       [62.3],
       [62.4],
       [62.5],
       [62.6],
       [62.7],
       [62.8],
       [62.9]])

In [33]:
grafico = px.scatter(x=X_planos_saude2.ravel(), y=y_planos_saude2)
grafico.add_scatter(
    x=X_teste_arvore.ravel(),
    y=regressor_arvore_saude.predict(X_teste_arvore),
    name='Regressão')
grafico.show()

### Base preço das casas

In [34]:
X_casas_train.shape

(15129, 16)

In [35]:
regressor_arvore_casas = DecisionTreeRegressor()
regressor_arvore_casas.fit(X_casas_train, y_casas_train)

DecisionTreeRegressor()

In [36]:
regressor_arvore_casas.score(X_casas_train, y_casas_train)

0.9992712177726063

In [37]:
regressor_arvore_casas.score(X_casas_test, y_casas_test)

0.7011732319717088

In [38]:
previsoes = regressor_arvore_casas.predict(X_casas_test)

In [39]:
previsoes

array([ 288000., 2340000.,  499000., ...,  289000.,  215000.,  205000.],
      shape=(6484,))

In [40]:
mean_absolute_error(y_casas_test, previsoes)

100059.42805367058

## Random Forest

### Base plano de Saúde

In [41]:
X_planos_saude2, y_planos_saude2

(array([[18],
        [23],
        [28],
        [33],
        [38],
        [43],
        [48],
        [53],
        [58],
        [63]]),
 array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
        10100]))

In [42]:
regressor_random_forest_saude = RandomForestRegressor(n_estimators=10)
regressor_random_forest_saude.fit(X_planos_saude2, y_planos_saude2)

RandomForestRegressor(n_estimators=10)

In [43]:
regressor_random_forest_saude.score(X_planos_saude2, y_planos_saude2)

0.9342587527735251

In [44]:
grafico = px.scatter(x=X_planos_saude2.ravel(), y=y_planos_saude2)
grafico.add_scatter(x=X_teste_arvore.ravel(), y=regressor_random_forest_saude.predict(X_teste_arvore), name='Regressão')
grafico.show()

### Base preço das casas

In [45]:
regressor_random_forest_casas = RandomForestRegressor(n_estimators=100)
regressor_random_forest_casas.fit(X_casas_train, y_casas_train)

RandomForestRegressor()

In [46]:
regressor_random_forest_casas.score(X_casas_train, y_casas_train)

0.9811824899644133

In [47]:
regressor_random_forest_casas.score(X_casas_test, y_casas_test)

0.8793633986658896

In [48]:
previsoes = regressor_random_forest_casas.predict(X_casas_test)
previsoes

array([ 312010.5 , 1704244.3 ,  539237.  , ...,  358976.78,  229720.21,
        199650.02], shape=(6484,))

In [49]:
mean_absolute_error(y_casas_test, previsoes)

67884.02916220269