# **ECLAT**

In [1]:
import os
from pathlib import Path

import pandas as pd
from pyECLAT import ECLAT

DRIVE_DIRECTORY = Path.cwd().parent / "data"

In [2]:
df_mercado1 = pd.read_csv(os.path.join(DRIVE_DIRECTORY, "mercado.csv"), header=None)
df_mercado1

          0        1         2         3
0     leite  cerveja       pao  manteiga
1      cafe      pao  manteiga       NaN
2      cafe      pao  manteiga       NaN
3     leite     cafe       pao  manteiga
4   cerveja      NaN       NaN       NaN
5  manteiga      NaN       NaN       NaN
6       pao      NaN       NaN       NaN
7    feijao      NaN       NaN       NaN
8     arroz   feijao       NaN       NaN
9     arroz      NaN       NaN       NaN

In [3]:
eclat = ECLAT(data=df_mercado1)
eclat.df_bin

   arroz  leite  cafe  pao  cerveja  feijao  manteiga
0      0      1     0    1        1       0         1
1      0      0     1    1        0       0         1
2      0      0     1    1        0       0         1
3      0      1     1    1        0       0         1
4      0      0     0    0        1       0         0
5      0      0     0    0        0       0         1
6      0      0     0    1        0       0         0
7      0      0     0    0        0       1         0
8      1      0     0    0        0       1         0
9      1      0     0    0        0       0         0

In [4]:
eclat.uniq_

[nan, 'arroz', 'leite', 'cafe', 'pao', 'cerveja', 'feijao', 'manteiga']

In [5]:
indices, suporte = eclat.fit(min_support=0.3, min_combination=1, max_combination=3)
indices

Combination 1 by 1

3it [00:00, 129.63it/s]

Combination 2 by 2

3it [00:00, 140.12it/s]

Combination 3 by 3

1it [00:00, 93.10it/s]

{'cafe': [1, 2, 3],
 'pao': [0, 1, 2, 3, 6],
 'manteiga': [0, 1, 2, 3, 5],
 'cafe & pao': [1, 2, 3],
 'cafe & manteiga': [1, 2, 3],
 'pao & manteiga': [0, 1, 2, 3],
 'cafe & pao & manteiga': [1, 2, 3]}

In [6]:
suporte

{'cafe': 0.3,
 'pao': 0.5,
 'manteiga': 0.5,
 'cafe & pao': 0.3,
 'cafe & manteiga': 0.3,
 'pao & manteiga': 0.4,
 'cafe & pao & manteiga': 0.3}